export const NAME_EPICS = {
    EPIC_CONTRACT_SCREEN: {
        EPIC_CONTRACT_SCREEN: 'EPIC_CONTRACT_SCREEN',
        EPIC_CONTRACT: 'EPIC_CONTRACT',
        EPIC_CONTRACT_FAILED: 'EPIC_CONTRACT_FAILED',

        EPIC_CONFIRM_CONTRACT: 'EPIC_CONFIRM_CONTRACT',
        EPIC_CONFIRM_CONTRACT_FAILED: 'EPIC_CONFIRM_CONTRACT_FAILED',
    }
}