export const NAME_EPICS = {
    EPIC_BILL_SCREEN: {
        EPIC_BILL_SCREEN: 'EPIC_BILL_SCREEN',
        EPIC_BILL: 'EPIC_BILL',
        EPIC_BILL_FAILED: 'EPIC_BILL_FAILED',
        
        EPIC_BILL_DETAIL: 'EPIC_BILL_DETAIL',
        EPIC_BILL_DETAIL_FAILED: 'EPIC_BILL_DETAIL_FAILED',
    }
}