export const NAME_ACTIONS = {
    LOGIN_SCREEN: {
        LOGIN_SCREEN: 'LOGIN_SCREEN',
        LOGIN: 'LOGIN',
        LOGIN_FAILED: 'LOGIN_FAILED',

        LOGOUT: 'LOGOUT',
        LOGOUT_FAILED: 'LOGOUT_FAILED',

        CHANGE_PASSWORD: 'CHANGE_PASSWORD',
        CHANGE_PASSWORD_FAILED: 'CHANGE_PASSWORD_FAILED',

        GET_RATING: "GET_RATING",
        GET_RATING_FAILED: "GET_RATING_FAILED",

        RATING: "RATING",
        RATING_FAILED: "RATING_FAILED"
    }
}