export const NAME_ACTIONS = {
    LOGIN_SCREEN: {
        LOGIN_SCREEN: 'LOGIN_SCREEN',
        LOGIN: 'LOGIN',
        LOGIN_FAILED: 'LOGIN_FAILED',

        LOGOUT: 'LOGOUT',
        LOGOUT_FAILED: 'LOGOUT_FAILED',

        CHANGE_PASSWORD:'CHANGE_PASSWORD',
        CHANGE_PASSWORD_FAILED:'CHANGE_PASSWORD_FAILED',
    }
}