export const NAME_ACTIONS = {
    CONTRACT_SCREEN: {
        CONTRACT_SCREEN: 'CONTRACT_SCREEN',
        CONTRACT: 'CONTRACT',
        CONTRACT_FAILED: 'CONTRACT_FAILED',

        CONFIRM_CONTRACT: 'CONFIRM_CONTRACT',
        CONFIRM_CONTRACT_FAILED: 'CONFIRM_CONTRACT_FAILED',
    }
}