export const NAME_EPICS = {
    EPIC_LOGIN_SCREEN: {
        EPIC_LOGIN_SCREEN: 'EPIC_LOGIN_SCREEN',
        EPIC_LOGIN: 'EPIC_LOGIN',
        EPIC_LOGIN_FAILED: 'EPIC_LOGIN_FAILED',

        EPIC_LOGOUT: 'EPIC_LOGOUT',
        EPIC_LOGOUT_FAILED: 'EPIC_LOGOUT_FAILED',

        EPIC_CHANGE_PASSWORD:'EPIC_CHANGE_PASSWORD',
        EPIC_CHANGE_PASSWORD_FAILED:'EPIC_CHANGE_PASSWORD_FAILED',

    }
}