export const NAME_EPICS = {
    EPIC_HOUSE_SCREEN: {
        EPIC_HOUSE_SCREEN: 'EPIC_HOUSE_SCREEN',
        EPIC_GET_HOUSE: 'EPIC_GET_HOUSE',
        EPIC_GET_HOUSE_FAILED: 'EPIC_GET_HOUSE_FAILED',
        EPIC_GET_LIST_ROOM: 'EPIC_GET_LIST_ROOM',
        EPIC_GET_LIST_ROOM_FAILED: 'EPIC_GET_LIST_ROOM_FAILED',
        EPIC_GET_HOUSE_TOP_RATE: 'EPIC_GET_HOUSE_TOP_RATE',
        EPIC_GET_HOUSE_TOP_RATE_FAILED: 'EPIC_GET_HOUSE_TOP_RATE_FAILED',
        EPIC_GET_ROOM_RELATE_POST: 'EPIC_GET_ROOM_RELATE_POST',
        EPIC_GET_ROOM_RELATE_POST_FAILED: 'EPIC_GET_ROOM_RELATE_POST_FAILED',
    }
}