export const NAME_EPICS = {
    EPIC_HOUSE_SCREEN: {
        EPIC_HOUSE_SCREEN: 'EPIC_HOUSE_SCREEN',
        EPIC_GET_HOUSE: 'EPIC_GET_HOUSE',
        EPIC_GET_HOUSE_FAILED: 'EPIC_GET_HOUSE_FAILED',
    }
}